// src/presentation/providers/SolanaProvider.tsx
"use client"

import { useMemo } from "react"
import { ConnectionProvider, WalletProvider } from "@solana/wallet-adapter-react"
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base"
import { PhantomWalletAdapter, SolflareWalletAdapter } from "@solana/wallet-adapter-wallets"
import { clusterApiUrl } from "@solana/web3.js"

// Default styles that can be overridden by your app
import "@solana/wallet-adapter-react-ui/styles.css"

export default function SolanaProvider({ children }: { children: React.ReactNode }) {
  // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'.
  const network = WalletAdapterNetwork.Mainnet

  // You can also provide a custom RPC endpoint.
  const endpoint = useMemo(() => clusterApiUrl(network), [network])

  const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new SolflareWalletAdapter(),
    ],
    []
  )

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        {children}
      </WalletProvider>
    </ConnectionProvider>
  )
}

// src/lib/components/web3/SolanaProvider.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { walletStore } from "$lib/stores/wallet";
    import {
        WalletProvider,
        ConnectionProvider,
    } from "@svelte-on-solana/wallet-adapter-core";
    import { WalletMultiButton } from "@svelte-on-solana/wallet-adapter-ui";
    import {
        PhantomWalletAdapter,
        SolflareWalletAdapter,
    } from "@solana/wallet-adapter-wallets";
    import { clusterApiUrl } from "@solana/web3.js";
    import "@svelte-on-solana/wallet-adapter-ui/styles.css";

    const network = clusterApiUrl("mainnet-beta");
    const wallets = [new PhantomWalletAdapter(), new SolflareWalletAdapter()];

    // Pass localStorage key to keep it persistent
    const localStorageKey = "solana-wallet";
</script>

<ConnectionProvider endpoint={network}>
    <WalletProvider {wallets} {localStorageKey} autoConnect>
        <slot />
    </WalletProvider>
</ConnectionProvider>
